Add collatz-conjecture
exercism/cairo pull request #114
Opened 2024-08-06 00:01 UTC by BNAndras

For #48in24.

`configlet create --practice-exercise <slug>` formats the track config so that's why the practices array for reverse string was edited. I used unsigned ints so the tests for zero or a negative number were skipped.

2024-08-06 08:59 UTC, misicnenad requested changes

2024-08-06 08:59 UTC, misicnenad commented on exercises/practice/collatz-conjecture/.meta/tests.toml
> +include = false
This test case _can_ be implemented, as zero is a valid unsigned int

2024-08-07 16:42 UTC, misicnenad requested changes

2024-08-07 16:42 UTC, misicnenad commented on exercises/practice/collatz-conjecture/.meta/example.cairo
> +    if number == 0 {
```suggestion
    assert!(number != 0, "Only positive integers are allowed");
```
Follows the [canonical data](https://github.com/exercism/problem-specifications/blob/main/exercises/collatz-conjecture/canonical-data.json#L48) more closely, which expects an actual error. This also removes the need for `Option`.

To test for this, you can use the `should_panic` attribute:
https://book.cairo-lang.org/ch10-01-how-to-write-tests.html#checking-for-panics-with-should_panic

2024-08-14 08:28 UTC, 0xNeshi approved these changes
Nice work

2024-08-14 08:28 UTC, merged