control flow concept updated
exercism/cairo pull request #117
Opened 2024-08-09 12:59 UTC by Falilah

2024-08-12 06:04 UTC, 0xNeshi requested changes
Really good job! Most of the comments are nits.

2024-08-12 06:04 UTC, 0xNeshi commented on concepts/control-flow/about.md
> +    let a: [felt; 5] = [10, 20, 30, 40, 50].span();
```suggestion
    let a = [10, 20, 30, 40, 50].span();
```

2024-08-12 06:04 UTC, 0xNeshi commented on concepts/control-flow/about.md
> +    for element: felt in a {
```suggestion
    for element in a {
```

2024-08-12 06:04 UTC, 0xNeshi commented on concepts/control-flow/introduction.md
> +Control flow in Cairo, through constructs like `if` expressions and `loops`, allows developers to direct the execution of their programs based on conditional logic or repetitive tasks. If expressions
```suggestion
Control flow in Cairo, through constructs like `if` expressions and loops, allows developers to direct the execution of their programs based on conditional logic or repetitive tasks. `if` expressions enable branching based on whether conditions evaluate to `true` or `false`, while loops (`loop`, `while`, `for`) facilitate repeated execution of code blocks until specific criteria are met. These constructs are crucial for implementing logic, iteration, and handling multiple conditions concisely, making them essential tools for writing efficient and dynamic code in Cairo.
```
Very nice intro

2024-08-12 06:04 UTC, 0xNeshi commented on concepts/control-flow/.meta/config.json
> +  "blurb": "Control flow in Cairo uses if expressions to conditionally execute code and loops to repeat code while a condition is true.",
```suggestion
  "blurb": "Control flow in Cairo uses `if` expressions to conditionally execute code and loops to run code repeatedly.",
```

2024-08-12 06:04 UTC, 0xNeshi commented on concepts/control-flow/.meta/config.json
> +  "authors": ["misicnenad", "Falilah"],
```suggestion
  "authors": ["Falilah"],
```
Most of the changes I recommended are nits, so no need to list me as a co-author. The honor is all yours :)

2024-08-12 06:04 UTC, 0xNeshi commented on concepts/control-flow/.meta/config.json
> +  "contributors": []
```suggestion
  "contributors": ["0xNeshi"]
```
I changed my GH username

2024-08-12 13:25 UTC, Falilah commented on concepts/control-flow/about.md
> +## Concise Control Flow with `if let` and `while let`
to get this point right, should it be be moved to `enum` concept or copied to` enum` concept ?

2024-08-16 08:34 UTC, 0xNeshi commented on concepts/control-flow/about.md
> +## Concise Control Flow with `if let` and `while let`
They should be moved, i.e. they should only appear in the "Enums" concept.
Created a new issue for this https://github.com/exercism/cairo/issues/123

2024-08-16 15:15 UTC, 0xNeshi commented on concepts/control-flow/about.md
> +## `If` Expressions
```suggestion
## `if` Expressions
```

2024-08-16 15:16 UTC, 0xNeshi commented on concepts/control-flow/about.md
> +`If` expressions in Cairo allow you to control the flow of execution based on conditional logic. They follow a structure where code is executed depending on whether a boolean condition evaluates to `
```suggestion
`if` expressions in Cairo allow you to control the flow of execution based on conditional logic. They follow a structure where code is executed depending on whether a boolean condition evaluates to `true` or `false`.
```

2024-08-16 15:21 UTC, 0xNeshi commented on concepts/control-flow/about.md
> +> Note: Cairo prevents us from running program with infinite loops by including a gas meter. The gas meter is a mechanism that limits the amount of computation that can be done in a program. Gas is a
```suggestion
> Note: Cairo prevents us from running a program with infinite loops by including a gas meter. The gas meter is a mechanism that limits the amount of computation that can be done in a program. Gas is a unit of measurement that expresses the computation cost of an instruction. When the gas meter runs out, the program will stop.
```

2024-08-16 15:22 UTC, 0xNeshi commented on concepts/control-flow/about.md
> +#### Returning Values from loops
```suggestion
#### Returning Values from Loops
```

2024-08-16 15:24 UTC, 0xNeshi commented on concepts/control-flow/introduction.md
> +Control flow in Cairo, through constructs like `if` expressions and loops, allows developers to direct the execution of their programs based on conditional logic or repetitive tasks. `If` expressions
```suggestion
Control flow in Cairo, through constructs like `if` expressions and loops, allows developers to direct the execution of their programs based on conditional logic or repetitive tasks. `if` expressions enable branching based on whether conditions evaluate to `true` or `false`, while loops (`loop`, `while`, `for`) facilitate repeated execution of code blocks until specific criteria are met. These constructs are crucial for implementing logic, iteration, and handling multiple conditions concisely, making them essential tools for writing efficient and dynamic code in Cairo.
```

2024-08-16 15:26 UTC, 0xNeshi commented on concepts/enums/about.md
> +`if let`
```suggestion
```

2024-08-16 15:26 UTC, 0xNeshi commented on concepts/enums/about.md
> +
```suggestion
```

2024-08-16 15:26 UTC, 0xNeshi commented on concepts/enums/about.md
> +Using `match` to handle an Option:
```suggestion
Using `match` to handle an `Option`:
```

2024-08-16 15:28 UTC, 0xNeshi commented on concepts/enums/about.md
> +let config_max: Option<felt> = Option::Some(5);
```suggestion
let config_max: Option<felt252> = Option::Some(5);
```

2024-08-16 15:29 UTC, 0xNeshi commented on concepts/enums/about.md
> +    Option::Some(max: felt) => println!("The maximum is configured to be {}", max),
```suggestion
    Option::Some(max) => println!("The maximum is configured to be {}", max),
```

2024-08-16 15:31 UTC, 0xNeshi commented on concepts/enums/about.md
> +let number: Option<felt>  = Option::Some(5);
```suggestion
let number: Option<felt252>  = Option::Some(5);
```

2024-08-16 15:31 UTC, 0xNeshi commented on concepts/enums/about.md
> +if let Option::Some(max: felt) = number {
```suggestion
if let Option::Some(max) = number {
```

2024-08-16 15:31 UTC, 0xNeshi commented on concepts/enums/about.md
> +You can also include else with if let:
```suggestion
You can also include an `else` with `if let`:
```

2024-08-16 15:32 UTC, 0xNeshi commented on concepts/enums/about.md
> +let mut count: felt = 0;
```suggestion
```
makes little sense given the example

2024-08-16 15:32 UTC, 0xNeshi commented on concepts/enums/about.md
> +    count += 1;
```suggestion
    println!("You got some other coin!");
```

2024-08-16 15:32 UTC, 0xNeshi commented on concepts/enums/about.md
> +`while let`:
```suggestion
```

2024-08-16 15:33 UTC, 0xNeshi commented on concepts/enums/about.md
> +The `while let` syntax loops over values, executing a block for each matching pattern.
```suggestion
The `while let` syntax loops over `Option` values, executing a block for each matching pattern.
```

2024-08-16 15:33 UTC, 0xNeshi commented on concepts/enums/about.md
> +    let mut arr: Array<felt> = array![1, 2, 3, 4, 5, 6, 7, 8, 9];
```suggestion
    let mut arr: Array<felt252> = array![1, 2, 3, 4, 5, 6, 7, 8, 9];
```

2024-08-16 15:33 UTC, 0xNeshi commented on concepts/enums/about.md
> +    let mut sum: felt = 0;
```suggestion
    let mut sum: felt252 = 0;
```

2024-08-16 15:34 UTC, 0xNeshi commented on concepts/enums/about.md
> +    while let Option::Some(value: felt) = arr.pop_front() {
```suggestion
    while let Option::Some(value) = arr.pop_front() {
```

2024-08-16 15:40 UTC, 0xNeshi commented on concepts/control-flow/about.md
> +`If` expressions and loops control the flow of execution in Cairo by:
```suggestion
`if` expressions and loops control the flow of execution in Cairo by:
```

2024-08-16 15:40 UTC, 0xNeshi commented on concepts/control-flow/about.md
> +- **`If` expressions** conditionally run code based on whether a condition evaluates to true.
```suggestion
- **`if` expressions** conditionally run code based on whether a condition evaluates to true.
```

2024-08-16 15:42 UTC, 0xNeshi approved these changes

2024-08-16 15:43 UTC, 0xNeshi commented on concepts/enums/about.md
> +
```suggestion
```

2024-08-16 15:44 UTC, 0xNeshi commented
I applied some nits to avoid bugging you about them.

Great work! :blush:

2024-08-16 15:44 UTC, merged

2024-08-16 19:39 UTC, Falilah commented
> I applied some nits to avoid bugging you about them.
> 
> Great work! 😊
Thank you ✅