Trait concepts
exercism/cairo pull request #135
Opened 2024-08-26 06:34 UTC by Ephraim-nonso

2024-09-01 10:59 UTC, 0xNeshi commented
I will check out the PR tomorrow, I've been a bit busy

2024-09-02 08:01 UTC, 0xNeshi commented on concepts/traits/about.md
> +Implementation, when imported, can be labeled as `impl` as an alternative name. This helps when instantiating a generic implementation for concrete types. Let's define a trivial `Two` implementation
```suggestion
Implementations can be aliased when imported, using the `impl` keyword. This helps when instantiating a generic implementation for concrete types. Let's define a trivial implementation of trait `Two` for all types that implement the `One` trait by simply adding twice the value of `One` and returning the summation. We can afterwards expose the `Two` implementation that works only for `u8` and `u128` types.
```
nit: wording

2024-09-02 08:06 UTC, 0xNeshi commented on concepts/traits/about.md
> +## Negative Implementation
Let's describe only the production-ready features of Cairo, not experimental ones. 
**Remove this section for now**, and we can add it back once Negative Impls are part of the core language. 

Created an issue to track this https://github.com/exercism/cairo/issues/143

2024-09-02 08:10 UTC, 0xNeshi commented on concepts/traits/introduction.md
> +In Cairo, a trait is a series of methods that can be implemented by a data type. When a trait is implemented for a type, the methods defined in that trait can be called on instances of that type. A t
```suggestion
In Cairo, a trait is a series of methods that can be implemented by a data type. When a trait is implemented for a type, the methods defined in that trait can be called on instances of that type. A trait can be defined with generic types, defining behavior shared by multiple data types.
```
nit: wording

2024-09-12 12:45 UTC, 0xNeshi commented
@Ephraim-nonso need any help? Let me know if you need me to further clarify some of my comments

2024-09-13 19:47 UTC, Ephraim-nonso commented
Hi. I'm sorry I had an issue with my working device. I've it all fixed now and will make the changes according to the comment this coming week.

2024-09-20 17:28 UTC, 0xNeshi requested changes
Just a few more small changes and we can merge

2024-09-20 17:28 UTC, 0xNeshi commented on concepts/traits/about.md
> +    }
The example does not compile due to the missing semicolon `;` here and the missing `Tweet` import. Add it and format the code.

2024-09-20 17:28 UTC, 0xNeshi commented on concepts/traits/about.md
> +    pub struct NewsArticle {
nit: format the code

2024-09-20 17:28 UTC, 0xNeshi commented on concepts/traits/about.md
> +    }; // Tweet instantiation
```suggestion
    };
```
nit

2024-09-21 15:51 UTC, 0xNeshi approved these changes
Very good work!

2024-09-21 15:51 UTC, merged

2024-09-21 15:53 UTC, Ephraim-nonso commented
Thank you. Apologies for the delayed work pace. I'd pick another.

2024-09-21 16:47 UTC, 0xNeshi commented
@Ephraim-nonso no problem, feel free to pick any issue you like