Add annalyns-infiltration
exercism/cairo pull request #154
Opened 2024-09-04 02:05 UTC by BNAndras

Towards #149.

The exemplar file will be shown to mentors during a mentoring discussion for this exercise as an example of a great solution at that point in the syllabus. Therefore, any and all nitpicks are appreciated keeping that in mind.

2024-09-04 03:51 UTC, BNAndras commented
configlet's not going to be happy until we deal with the `functions` prerequisite. No concept exercises teach that at the moment so this will be an issue for the `cars-assemble` exercise as well. It might be easier to have some placeholder exercises for these prerequisites set up. Then you solicit PRs to fill those exercises with working implementations. Before the syllabus goes live, all those placeholders will need to be dealt with so students can unlock exercises as they go through the syllabus.

2024-09-04 09:26 UTC, 0xNeshi commented
Will create stubs, great suggestion :heart:

2024-09-04 14:24 UTC, 0xNeshi requested changes

2024-09-04 14:24 UTC, 0xNeshi commented on exercises/concept/annalyns-infiltration/.docs/instructions.md
> +```cairo
``````suggestion
```rust
``````

There is no Cairo highlight atm

2024-09-04 14:24 UTC, 0xNeshi commented on exercises/concept/annalyns-infiltration/.docs/introduction.md
> +let has_error = false; // boolean variable 'hasError' set to 'false'
```suggestion
let has_error = false; // boolean variable 'has_error' set to 'false' 
```

2024-09-04 14:24 UTC, 0xNeshi commented on exercises/concept/annalyns-infiltration/.meta/exemplar.cairo
> +    return !knight_awake;
```suggestion
    !knight_awake
```
nit: returning a value _without_ using `return` is a more "Cairo" way, update the other returns as well

2024-09-04 15:27 UTC, 0xNeshi commented
This PR https://github.com/exercism/cairo/pull/156 should fix the configlet problem

2024-09-06 20:01 UTC, BNAndras commented
So `configlet lint` apparently doesn't consider WIP exercises when it checks if a prerequisite is in the concepts array. If we set the status of `lucians-luscious-lasagna` to beta or active, that warning goes away. https://exercism.org/docs/building/tracks/config-json#h-metadata seems to suggest concept exercises won't show up until we set `concept_exercises` to true. However, that might be referring to the Learn tab that contains the syllabus. I've never worked on an Exercism syllabus.

2024-09-07 09:33 UTC, 0xNeshi commented
> So configlet lint apparently doesn't consider WIP exercises when it checks if a prerequisite is in any exercise's concepts array.

That's what I figured as well.

> If we set the status of lucians-luscious-lasagna to beta or active, that warning goes away.

Maybe we should put all exercises to `wip` status for now, as there might be changes as we add them and I figure out how I'd like to organize the syllabus.

>  https://exercism.org/docs/building/tracks/config-json#h-metadata seems to suggest concept exercises won't show up until we set concept_exercises to true.

I think this is the case as well. We will enable the syllabus only once all the concept exercises are added.

2024-09-09 08:14 UTC, 0xNeshi approved these changes

2024-09-09 08:14 UTC, merged