prime_factors
exercism/cairo pull request #282
Opened 2024-09-16 12:05 UTC by Falilah

2024-09-20 08:29 UTC, 0xNeshi commented
Hi, thanks for the PR! Will be taking a look later in the day

2024-09-20 18:16 UTC, 0xNeshi requested changes
Very good job! Left some relatively minor comments, we can merge immediately after those are addressed

2024-09-20 18:16 UTC, 0xNeshi commented on exercises/practice/nth-prime/tests/nth_prime.cairo
> +#[should_panic(expected: ("there is no zeroth prime",))]
```suggestion
#[ignore]
#[should_panic(expected: ("there is no zeroth prime",))]
```
forgot to ignore the test

2024-09-20 18:16 UTC, 0xNeshi commented on exercises/practice/prime-factors/.meta/example.cairo
> +        for i in 2..(num + 1) {
Although this works, it seems kind of redundant to continuously recreate a for loop + range that goes to `num + 1`, but then almost never reach it. 
Example solutions are there to showcase an idiomatic way to solve the problem for a given language, so we need to pay attention to clean code.
There is a way to write this function without depending on breaks and never-to-be-reached ranges, try to rewrite it in such a way. You can use [Rust's](https://github.com/exercism/rust/blob/main/exercises/practice/prime-factors/.meta/example.rs) implementation as inspiration.

2024-09-20 19:09 UTC, Falilah commented on exercises/practice/nth-prime/tests/nth_prime.cairo
> +fn big_prime() {
making it compliant with canonical data which is 10001 is throwing `out of gas` error when tested, that is why I reduced the value to 500, what do you think we do?

2024-09-21 15:42 UTC, 0xNeshi commented on exercises/practice/nth-prime/tests/nth_prime.cairo
> +fn big_prime() {
Hmm, try rerunning the test with an [updated implementation](https://github.com/exercism/cairo/pull/282#discussion_r1769008529). Note that if you reuse Rust's implementation, you can increase `possible` by 2 to look only at odd numbers, thus improving efficiency potentially by 2x. Let me know if that works

2024-09-21 17:40 UTC, 0xNeshi commented on exercises/practice/nth-prime/tests/nth_prime.cairo
> +fn big_prime() {
Let's leave the test in with a smaller value than in canonical data, but let's also make 2 changes:
1. increase the value to `4001` and the expected value to `37831` 
2. add a comment to [tests.toml below this test description](https://github.com/exercism/cairo/pull/282/files#diff-14a49407b23723cb62218e8d3afd6491c34a4d2d81dd7b434740bf80b8648e51R22) stating: `comment = "decreased the input value to fit into Cairo's runtime limitation"

2024-09-21 18:54 UTC, Falilah commented on exercises/practice/nth-prime/tests/nth_prime.cairo
> +fn big_prime() {
I increased the value to 4001, it is  passing locally but the workflow timed out with `out of gas`. I then bring it down to  500 which was what i had before, the  run is still failing with `out of gas`. I have left it in the suggested value which is 4001, kindly help look into the job being run.

2024-09-22 06:51 UTC, 0xNeshi commented on exercises/practice/nth-prime/tests/nth_prime.cairo
> +fn big_prime() {
The problem is not with `nth_prime`, but with `prime-factors` :D But there is an `out of gas` issue there.
You can solve the issue by the following optimizations:
- first handle all divisions by `2`, which is the only even prime number
- then starting from `3`, check for prime factors, increasing the possible prime not by 1, but by 2

```rust
pub fn factors(n: u64) -> Array<u64> {
    let mut val = n;
    let mut out: Array<u64> = ArrayTrait::new();

    if val < 2 {
        return out;
    }

    while val % 2 == 0 {
        out.append(2);
        val /= 2;
    };

    let mut possible = 3;
    while val != 1 {
        while val % possible == 0 {
            out.append(possible);
            val /= possible;
        };
        possible += 2;
    };

    out
}
```

2024-09-22 13:55 UTC, Falilah commented on exercises/practice/nth-prime/tests/nth_prime.cairo
> +fn big_prime() {
oooh my bad too, I had the prime numbers all passing before I started the nth, but I guess I did not pay enough attention to the details od the workflow

2024-09-22 14:03 UTC, Falilah commented on exercises/practice/nth-prime/tests/nth_prime.cairo
> +fn big_prime() {
seems we are good now. I have adjusted the solution according to yours.
let me know if there is any changes to be made

2024-09-23 07:40 UTC, 0xNeshi commented on exercises/practice/nth-prime/tests/nth_prime.cairo
> +fn big_prime() {
All good now

2024-09-23 07:41 UTC, 0xNeshi approved these changes
Very good work!

2024-09-23 07:41 UTC, merged