All your base
exercism/cairo pull request #295
Opened 2024-10-11 23:50 UTC by Falilah

2024-10-12 13:30 UTC, 0xNeshi requested changes

2024-10-12 13:30 UTC, 0xNeshi commented on exercises/practice/all-your-base/src/lib.cairo
> +pub fn convert(number: Array<u32>, from_base: u32, to_base: u32) -> Result<Array<u32>, Error> {
Rename the function to `rebase` to align it with [canonical data](https://github.com/exercism/problem-specifications/blob/main/exercises/all-your-base/canonical-data.json#L18)

2024-10-12 13:30 UTC, 0xNeshi commented on config.json
> +        "difficulty": 1
This is a harder exercise, set it to at least 4

2024-10-12 13:30 UTC, 0xNeshi commented on exercises/practice/all-your-base/tests/all_your_base.cairo
> +    let expected_output: Array<u32> = array![1];
```suggestion
    let expected_output = Result::Ok(array![1]);
```
and later below:
```rust
assert_eq!(result, expected_output);
```
It's cleaner

2024-10-14 05:30 UTC, 0xNeshi approved these changes
Good job! Polished some things for you, to speed up the review

2024-10-14 05:30 UTC, 0xNeshi commented on exercises/practice/all-your-base/src/lib.cairo
> +pub fn rebase(digits: Array<u32>, inputBase: u32, outputBase: u32) -> Result<Array<u32>, Error> {
```suggestion
pub fn rebase(digits: Array<u32>, input_base: u32, output_base: u32) -> Result<Array<u32>, Error> {
```
snake_case is idiomatic

2024-10-14 05:31 UTC, merged

2024-10-14 09:02 UTC, Falilah commented
> Good job! Polished some things for you, to speed up the review

Thank you